#!/bin/bash
# /etc/init.d/catfeeder

### BEGIN INIT INFO
# Provides:          catfeeder
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage a catfeeder
### END INIT INFO


case "$1" in
    start)
        echo "Starting catfeeder"
        /usr/bin/python /home/pi/catfeeder.py
        ;;
    stop)
        echo "Stopping catfeeder"
        killall catfeeder
        ;;
    *)
        echo "Usage: /etc/init.d/catfeeder start|stop"
        exit 1
        ;;
esac

exit 0
